/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'street' : string,
  'city' : string,
  'state' : string,
  'pincode' : string,
}
export interface Preorder {
  'id' : bigint,
  'status' : string,
  'paymentMethod' : string,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'address' : Address,
  'quantity' : bigint,
  'phone' : string,
}
export type Time = bigint;
export interface VisitStats {
  'today' : bigint,
  'last7Days' : bigint,
  'yesterday' : bigint,
}
export interface _SERVICE {
  'getAllPreorders' : ActorMethod<[], Array<Preorder>>,
  'getTotalPreorders' : ActorMethod<[], bigint>,
  'getVisitStats' : ActorMethod<[], VisitStats>,
  'recordVisit' : ActorMethod<[], undefined>,
  'submitPreorder' : ActorMethod<
    [string, string, string, string, string, string, string, bigint],
    bigint
  >,
  'updateOrderStatus' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];