/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Address = IDL.Record({
  'street' : IDL.Text,
  'city' : IDL.Text,
  'state' : IDL.Text,
  'pincode' : IDL.Text,
});
export const Preorder = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'address' : Address,
  'quantity' : IDL.Nat,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllPreorders' : IDL.Func([], [IDL.Vec(Preorder)], ['query']),
  'getTotalPreorders' : IDL.Func([], [IDL.Nat], ['query']),
  'submitPreorder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Address = IDL.Record({
    'street' : IDL.Text,
    'city' : IDL.Text,
    'state' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const Preorder = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'address' : Address,
    'quantity' : IDL.Nat,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllPreorders' : IDL.Func([], [IDL.Vec(Preorder)], ['query']),
    'getTotalPreorders' : IDL.Func([], [IDL.Nat], ['query']),
    'submitPreorder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };